[[ -z "$1" ]] && echo "NEED 1st arugment!" && return
[[ -z "$2" ]] && echo "NEED 2nd arugment!" && return

[[ -z "$EXAMPLEFILE" ]] && echo "please source the setup script" && return
[[ ! -d outputbatch ]] && mkdir outputbatch
htagNew=$1
htagOld=$2

sed -i "s|^export BASEDIR=.*|export BASEDIR=${BASEDIR}|g" $BASEDIR/AllCutflows/getCutflowsBatch.sh


echo ${VARSFORCUTFLOWS[@]} | sed 's/ /, /g' | sed 's/^/enum CutEnum {/g' | sed 's/$/};/g' > $BASEDIR/AllCutflows/cutflow_vars.h
echo '// This file is automatically generated by getCutflows.sh.  To change the cutflows variables, change the setup script' >> $BASEDIR/AllCutflows/cutflow_vars.h

echo Submitting batch job for cutflows... This takes 30mins-1h to finish

bsub -q 1nd $BASEDIR/AllCutflows/getCutflowsBatch.sh $htagNew $htagOld
