# script to get the cutflows all of the MxAODs in a release (e.g. h011).  Meant to run on lxplus batch system. Called by batchSubmitter.sh in this folder.
# Creates the txt files with cutflows and then copies them to the samples/HTAG/ directory

[[ -z "$1" ]] && echo "NEED 1st arugment! newHtag e.g. h011" && exit 1
# This base dir is automatically set by batchSubmitter, changing it will do nothing since it will be reset
export BASEDIR=/afs/cern.ch/user/a/athompso/www

source /afs/cern.ch/project/eos/installation/atlas/etc/setup.sh
source $BASEDIR/setup.sh

echo started $0 at $(date)
htagNew=$1

[[ -z "$datasetDir" ]] && echo Please source the setup script!! && exit
[[ ! -d cutflows ]] && mkdir cutflows
[[ ! -d cutflows/$htagNew ]] && mkdir cutflows/$htagNew
#echo ${VARSFORCUTFLOWS[@]} | sed 's/ /, /g' | sed 's/^/enum CutEnum {/g' | sed 's/$/};/g' > cutflow_vars.h
#echo '// This file is automatically generated by getCutflows.sh.  To change the cutflows variables, change the setup script' >> cutflow_vars.h

SampleDirs=()
SampleDirs+=($(eos ls $datasetDir/$htagNew/))

Samples=()
for DIR in ${SampleDirs[@]}; do
  Samples+=($(eos ls $datasetDir/$htagNew/$DIR/ | grep .root ))
  [[ $DIR =~ data ]] && Samples+=($(eos ls $datasetDir/$htagNew/$DIR/runs/ | grep .root))
  #break
done

echo "Making Cutflows for all samples on EOS for $htagNew..."

for fileName in ${Samples[@]}; do
    file=""
    for DIR in ${SampleDirs[@]}; do
      [[ ! -z "$(eos ls $datasetDir/$htagNew/$DIR/$fileName 2>/dev/null)"  ]] && file="$EOSMOUNTDIR/$datasetDir/$htagNew/$DIR/$fileName" && sampleDir=$DIR
      [[ ! -z "$(eos ls $datasetDir/$htagNew/$DIR/runs/$fileName 2>/dev/null)"  ]] && file="$EOSMOUNTDIR/$datasetDir/$htagNew/$DIR/runs/$fileName" && sampleDir=$DIR/runs
    done
    echo $file
    base=$(basename ${file})
    fileType=${fileName%.MxAOD*}
    cutFlowName=CutFlow_$fileType

    nFiles=$(eos ls $datasetDir/$htagNew/$sampleDir/$fileName | wc -l)
    if [[ $fileName =~ ^data ]]; then
      root -l -q -b "$BASEDIR/AllCutflows/printCutflowData.c(\"${file}\")" 2>err.log 1> cutflows/$htagNew/${fileName}.txt
      #root -l -q -b "$BASEDIR/AllCutflows/printCutflowData.c(\"${file}\")"
    else
      root -l -q -b "$BASEDIR/AllCutflows/printCutflow.c(\"${file}\",${nFiles},\"${cutFlowName}\")"  2>err.log 1> cutflows/$htagNew/${fileName}.txt
      #root -l -q -b "$BASEDIR/AllCutflows/printCutflow.c(\"${file}\",${nFiles},\"${cutFlowName}\")"
    fi
    sed -i'.og' "1d" cutflows/$htagNew/${fileName}.txt
    sed -i'.og' "s/^ *//g" cutflows/$htagNew/${fileName}.txt
    sed -i'.og' "s/Processing.*/                    $fileType/g" cutflows/$htagNew/${fileName}.txt
    cp cutflows/$htagNew/${fileName}.txt $BASEDIR/AllCutflows/cutflows/$htagNew/
done

