# dumps the cutflows of the mH=125 MxAODs to txt files, which are read by index.php
[[ -z "$1" ]] && echo Please enter an htag as an argument! E.G source getCutflows.sh h011 h010 && return
[[ -z "$2" ]] && echo Please enter an htag as an argument! E.G source getCutflows.sh h011 h010 && return
echo started $0 at $(date)

htagNew=$1
htagOld=$2

[[ -z "$datasetDir" ]] && echo Please source the setup script!! && return
[[ ! -d "$EOSMOUNTDIR/$datasetDir" ]] && echo EOS not mounted!  Please mount EOS in the base directory \(maybe it failed during setup?\) && return
echo ${VARSFORCUTFLOWS[@]} | sed 's/ /, /g' | sed 's/^/enum CutEnum {/g' | sed 's/$/};/g' > cutflow_vars.h
echo '// This file is automatically generated by getCutflows.sh.  To change the cutflows variables, change the setup script' >> cutflow_vars.h

for htag in $htagNew $htagOld; do
  #break 
  Samples=()
  for DIR in ${MXAODDIRS[@]}; do
    Samples+=($(eos ls $datasetDir/$htag/$DIR/  ))
    #break
  done
  
  echo "Making Cutflows for all samples on EOS for $htag..."
  
  for fileName in ${Samples[@]}; do
      file=""
      for DIR in ${MXAODDIRS[@]}; do
        #[[ ! -z "$(eos ls $datasetDir/$htag/$DIR/$fileName 2>/dev/null)"  ]] && file="root://eosatlas.cern.ch/$datasetDir/$htag/$DIR/$fileName" && sampleDir=$DIR
        [[ ! -z "$(eos ls $datasetDir/$htag/$DIR/$fileName 2>/dev/null)"  ]] && file="$EOSMOUNTDIR/$datasetDir/$htag/$DIR/$fileName" && sampleDir=$DIR
      done
      #file="root://eosatlas.cern.ch/$datasetDir/$htag/$mcDir/$fileName"
      echo $file
      base=$(basename ${file})
      fileType=${fileName%.MxAOD*}
      cutFlowName=CutFlow_$fileType

      nFiles=$(eos ls $datasetDir/$htag/$sampleDir/$fileName | wc -l)
      if [[ $fileName =~ $DATANAME ]]; then
        root -l -q -b "printCutflowData.c(\"${file}\")" 2>err.log 1> cutflows/${fileName}.txt
        #root -l -q -b "printCutflowData.c(\"${file}\")" 
      else
        root -l -q -b "printCutflow.c(\"${file}\",${nFiles},\"${cutFlowName}\")" 2>err.log 1> cutflows/${fileName}.txt
        #root -l -q -b "printCutflow.c(\"${file}\",${nFiles},\"${cutFlowName}\")" 
      fi
      sed -i'.og' "1d" cutflows/${fileName}.txt
      sed -i'.og' "s/^ *//g" cutflows/${fileName}.txt
      sed -i'.og' "s/Processing.*/                    $fileType/g" cutflows/${fileName}.txt
  done
  

done
Samples=()
for DIR in ${MXAODDIRS[@]}; do
  Samples+=($(eos ls $datasetDir/$htagNew/$DIR/  ))
  #break
done

# make diff cutflows to compare old and new cutflows
for filename in ${Samples[@]}; do
  fileType=${filename%.MxAOD*}
  for DIR in ${MXAODDIRS[@]}; do
    [[ ! -z "$(eos ls $datasetDir/$htagNew/$DIR/$filename 2>/dev/null)"  ]] && fileNew="root://eosatlas.cern.ch/$datasetDir/$htagNew/$DIR/$filename" && sampleDir=$DIR
    #eos ls $datasetDir/$htag/$DIR/$fileName
    #echo $datasetDir/$htag/$DIR/$fileName
  done
  #echo $sampleDir
  oldCutflowName=$(eos ls $datasetDir/$htagOld/$sampleDir/ | grep ${fileType}.MxAOD)
  echo $fileType
  diffCutflowName=$(echo $filename | sed "s/h[0-9][0-9][0-9]/diff/g")
  #oldCutflowName=$(echo $filename | sed "s/h[0-9][0-9][0-9]/$htagOld/g")
  [[ -z "$oldCutflowName" ]] && echo $htagOld version of $fileType in $sampleDir does not exist! skipping...  && continue
  ptag=${filename%.h[0-9][0-9][0-9]*}
  ptag=${ptag#*MxAOD*.}
  oldptag=${oldCutflowName%.h[0-9][0-9][0-9]*}
  oldptag=${oldptag#*MxAOD*.}
  #echo $filename
  #echo $ptag
  #echo $oldCutflowName
  #echo $oldptag
  sed -i'.og' "1d" cutflows/${diffCutflowName}.txt
  #newCutflowName=$(echo $filename | sed "s/h[0-9][0-9][0-9]/$htagNew/g")
  ./diffCutflow.py cutflows/${oldCutflowName}.txt cutflows/${filename}.txt && \
    sed -i'.og' "1 i\             $fileType" cutflows/${diffCutflowName}.txt
  [[ "$ptag" != "$oldptag" ]] && sed -i'.og' "1 i\ pTags are different! New is $ptag, old is $oldptag" cutflows/${diffCutflowName}.txt
  #[[ "$ptag" != "$oldptag" ]] && echo ptags are different!
done
rm cutflows/*.og
echo ended $0 at $(date)



